#include "encoder.h"

void Encoder_Init(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	GPIOA->MODER &= ~(GPIO_MODER_MODER6 | GPIO_MODER_MODER7 );
	GPIOA->MODER |= GPIO_MODER_MODER6_1 | GPIO_MODER_MODER7_1;
	GPIOA->PUPDR |= GPIO_PUPDR_PUPDR6_0 | GPIO_PUPDR_PUPDR7_0;
	//GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_6 | GPIO_OTYPER_OT_7);
	//GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6 | GPIO_OSPEEDER_OSPEEDR7;
	GPIOA->AFR[0] |= GPIO_AFRL_AFRL6_1 | GPIO_AFRL_AFRL7_1;
	TIM3->SMCR = TIM_SMCR_SMS_0;
	TIM3->CCMR1 = TIM_CCMR1_CC1S_0 | TIM_CCMR1_CC2S_0;
	TIM3->CCER = TIM_CCER_CC1P | TIM_CCER_CC2P;
	TIM3->PSC = 0;   				// Выставляем время 1 тика таймера
	TIM3->ARR = 1000;   					// До скольки считаем
	TIM3->CR1 |= TIM_CR1_CEN;
	TIM3->CNT = 500;
}
