#include "gpio.h"

void GPIO_Init (void){
	
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOD->MODER |= GPIO_MODER_MODER15_0;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR15_0;
	GPIOD->MODER |= GPIO_MODER_MODER13_0;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_0;
	GPIOD->MODER |= GPIO_MODER_MODER12_0;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR12_0;
	GPIOD->MODER |= GPIO_MODER_MODER14_0;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR14_0;
	GPIOA->MODER &= ~GPIO_MODER_MODER0;
	GPIOA->PUPDR = ((GPIOA->PUPDR & ~GPIO_PUPDR_PUPD0 ) | GPIO_PUPDR_PUPD0_1);
	
}
